//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('AudioCall')
export class AudioCallEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  callID: string;

  @Column('integer', { nullable: true })
  participants: number;

  @Column('date', { nullable: true })
  startTime: Date;

  @Column('date', { nullable: true })
  endTime: Date;

  @Column('text', { nullable: true })
  callTitle: string;

  @Column('text', { nullable: true })
  callStatus: string;
}
