//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Message')
export class MessageEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  sender: number;

  @Column('integer', { nullable: true })
  receiver: number;

  @Column('text', { nullable: true })
  messageContent: string;

  @Column('text', { nullable: true })
  subject: string;

  @Column('date', { nullable: true })
  timestamp: Date;
}
