//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('NoticeBoard')
export class NoticeBoardEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  noticeID: string;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  content: string;

  @Column('integer', { nullable: true })
  author: number;

  @Column('integer', { nullable: true })
  targetAudience: number;

  @Column('date', { nullable: true })
  publicationDate: Date;
}
