//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UserList, UserCreate, UserEdit } from './resources/User';
import { PostList, PostCreate, PostEdit } from './resources/Post';
import { MessageList, MessageCreate, MessageEdit } from './resources/Message';
import {
  VideoCallList,
  VideoCallCreate,
  VideoCallEdit,
} from './resources/VideoCall';
import {
  AudioCallList,
  AudioCallCreate,
  AudioCallEdit,
} from './resources/AudioCall';
import { GroupList, GroupCreate, GroupEdit } from './resources/Group';
import {
  NoticeBoardList,
  NoticeBoardCreate,
  NoticeBoardEdit,
} from './resources/NoticeBoard';
import UserIcon from '@mui/icons-material/AccountCircle';
import PostIcon from '@mui/icons-material/PostAdd';
import MessageIcon from '@mui/icons-material/Message';
import VideoCallIcon from '@mui/icons-material/VideoCall';
import AudioCallIcon from '@mui/icons-material/Call';
import GroupIcon from '@mui/icons-material/Group';
import NoticeBoardIcon from '@mui/icons-material/Announcement';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a0809a58f">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="User"
          options={{ label: 'User' }}
          list={UserList}
          create={UserCreate}
          edit={UserEdit}
          recordRepresentation="name"
          icon={UserIcon}
        />
        <Resource
          name="Post"
          options={{ label: 'Post' }}
          list={PostList}
          create={PostCreate}
          edit={PostEdit}
          recordRepresentation="title"
          icon={PostIcon}
        />
        <Resource
          name="Message"
          options={{ label: 'Message' }}
          list={MessageList}
          create={MessageCreate}
          edit={MessageEdit}
          recordRepresentation="messageContent"
          icon={MessageIcon}
        />
        <Resource
          name="VideoCall"
          options={{ label: 'Video Call' }}
          list={VideoCallList}
          create={VideoCallCreate}
          edit={VideoCallEdit}
          recordRepresentation="callID"
          icon={VideoCallIcon}
        />
        <Resource
          name="AudioCall"
          options={{ label: 'Audio Call' }}
          list={AudioCallList}
          create={AudioCallCreate}
          edit={AudioCallEdit}
          recordRepresentation="callID"
          icon={AudioCallIcon}
        />
        <Resource
          name="Group"
          options={{ label: 'Group' }}
          list={GroupList}
          create={GroupCreate}
          edit={GroupEdit}
          recordRepresentation="groupName"
          icon={GroupIcon}
        />
        <Resource
          name="NoticeBoard"
          options={{ label: 'Notice Board' }}
          list={NoticeBoardList}
          create={NoticeBoardCreate}
          edit={NoticeBoardEdit}
          recordRepresentation="title"
          icon={NoticeBoardIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
