//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Our app" />
    <CardContent>
      Make a awesome app for social media chating, posting, video and audio
      calling for a group. Add facilities of create account and search account.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
